import re

# Each entry: (id, name, specialty_list, city, state, abbr, rating, reviewCount, yrs, verified, responseTime, priceRange, bio, completedJobs, tags_list)
new_contractors = [
  # ── GEORGIA (GA) – missing: Electrical, Foundation, Plumbing, Roof ──────────
  ("ct61","Peach State Foundation Repair",["Foundation"],"Atlanta","Georgia","GA",4.8,312,19,True,"1-2 days","$$","Atlanta's most trusted foundation specialists. Pier and beam, slab crack repair, crawl space waterproofing, and lifetime-warranted drainage solutions for Georgia's expansive clay soil.",3800,["Pier and beam","Slab repair","Waterproofing","Lifetime warranty"]),
  ("ct62","Georgia Roofing Pros",["Roof","Exterior"],"Savannah","Georgia","GA",4.7,287,14,True,"Same day","$$","Serving coastal and metro Georgia. Storm and wind damage specialists, architectural shingle replacement, and flat roof systems. We work directly with your insurance company.",4200,["Storm damage","Insurance claims","Free inspection","Statewide GA"]),
  ("ct63","Atlanta Electric Solutions",["Electrical","Safety"],"Atlanta","Georgia","GA",4.7,341,16,True,"< 3 hours","$$","Licensed Atlanta electricians. Panel upgrades, EV charger installs, whole-home surge protection, and knob-and-tube replacement. Serving metro Atlanta and surrounding counties.",2900,["Panel upgrade","EV charger","Licensed","Metro Atlanta"]),
  ("ct64","Georgia Plumbing Experts",["Plumbing"],"Marietta","Georgia","GA",4.6,256,11,True,"< 2 hours","$$","Marietta plumbing for greater Atlanta metro. Water heater replacement, sewer line repair, slab leak detection, and 24/7 emergency service throughout Cobb, Fulton, and Gwinnett counties.",3100,["Slab leak","24/7","Sewer repair","Metro Atlanta"]),

  # ── FLORIDA (FL) – missing: Exterior, Foundation, Interior, Roof ─────────────
  ("ct65","Florida Foundation Experts",["Foundation"],"Orlando","Florida","FL",4.8,289,21,True,"1-2 days","$$","Central Florida's leading foundation company. Sinkhole assessment, concrete leveling, underpinning, and crawl space encapsulation. We deal with Florida's unique limestone and sandy soil challenges.",3600,["Sinkhole","Concrete leveling","Sandy soil","Central FL"]),
  ("ct66","Sunshine State Roofing",["Roof","Exterior"],"Jacksonville","Florida","FL",4.7,412,15,True,"Same day","$$","Jacksonville roofing specialists for hurricane season prep and storm damage restoration. Metal roofing, tile roofing, and emergency tarping. Insurance claim experts.",5100,["Hurricane prep","Metal roofing","Tile roofing","Insurance claims"]),
  ("ct67","Florida Home Renovations",["Interior","Exterior"],"Miami","Florida","FL",4.6,378,9,True,"Same day","$","Miami general contractor for interior remodels, hurricane impact windows, and exterior updates. Kitchen and bath specialists with 9 years serving South Florida homeowners.",4800,["Hurricane windows","Kitchen remodel","Bath remodel","South FL"]),

  # ── CALIFORNIA (CA) – missing: Electrical, Foundation, HVAC, Interior ────────
  ("ct68","Bay Area Foundation Repair",["Foundation"],"Oakland","California","CA",4.8,267,18,True,"1-2 days","$$$","Oakland foundation and seismic retrofitting specialists. Earthquake preparedness, cripple wall bracing, pier and beam repairs, and hillside stabilization for Bay Area homes.",3200,["Seismic retrofit","Hillside stabilization","Pier and beam","Bay Area"]),
  ("ct69","SoCal Electrical Group",["Electrical","Safety"],"San Diego","California","CA",4.7,389,14,True,"< 3 hours","$$$","San Diego licensed electricians. Solar panel wiring, panel upgrades, smart home systems, and EV charger installations. SDG&E rebate application assistance.",3800,["Solar wiring","EV charger","Smart home","San Diego"]),
  ("ct70","California HVAC Pros",["HVAC"],"Fresno","California","CA",4.7,312,12,True,"< 2 hours","$$","Fresno and Central Valley HVAC specialists. Evaporative cooler service, central AC installation, heat pump systems, and duct sealing for California's hot inland climate.",2700,["Evaporative cooler","Heat pump","Duct sealing","Central Valley"]),
  ("ct71","LA Home Interiors",["Interior","Exterior"],"Los Angeles","California","CA",4.6,445,7,True,"Same day","$$$","Los Angeles general contractor for ADU construction, kitchen and bathroom remodels, and outdoor living spaces. Licensed, bonded, and fully permitted work.",5200,["ADU construction","Kitchen remodel","Outdoor living","LA county"]),

  # ── ARIZONA (AZ) – missing: Electrical, Foundation, HVAC, Interior ──────────
  ("ct72","Desert Foundation Repair",["Foundation"],"Phoenix","Arizona","AZ",4.8,198,22,True,"1-2 days","$$","Phoenix foundation specialists dealing with Arizona's expansive soil and caliche layer. Concrete leveling, pier installation, and crack injection with 20-year warranty.",2600,["Expansive soil","Caliche","Concrete leveling","Phoenix metro"]),
  ("ct73","Arizona HVAC Experts",["HVAC"],"Scottsdale","Arizona","AZ",4.8,489,11,True,"< 1 hour","$$","Scottsdale AC specialists. We understand desert heat — emergency AC repair, heat pump installation, and whole-home duct sealing. 24/7 service in summer months.",6100,["Emergency AC","24/7 summer","Heat pump","Phoenix/Scottsdale"]),
  ("ct74","Phoenix Electric Solutions",["Electrical","Safety"],"Chandler","Arizona","AZ",4.7,234,13,True,"< 3 hours","$$","Chandler and East Valley licensed electricians. Solar battery backup systems, panel upgrades, EV chargers, and smart home wiring.",2100,["Solar battery","EV charger","Panel upgrade","East Valley"]),
  ("ct75","AZ Home Renovations",["Interior","Exterior"],"Tempe","Arizona","AZ",4.6,312,8,True,"Same day","$$","Tempe general contractor. Patio covers, cool deck resurfacing, kitchen updates, and outdoor kitchen installs. We specialize in desert-climate home improvements.",3400,["Patio cover","Cool deck","Outdoor kitchen","Tempe area"]),

  # ── NORTH CAROLINA (NC) – missing: Exterior, Foundation, HVAC, Interior, Plumbing ──
  ("ct76","Carolina Foundation Solutions",["Foundation"],"Greensboro","North Carolina","NC",4.8,234,17,True,"1-2 days","$$","Greensboro foundation repair and crawl space specialists. Pier and beam leveling, encapsulation, French drain systems for the Piedmont's red clay soil.",2800,["Pier and beam","Crawl space","Red clay soil","Piedmont NC"]),
  ("ct77","NC HVAC Specialists",["HVAC","Plumbing"],"Durham","North Carolina","NC",4.7,298,12,True,"< 2 hours","$$","Durham HVAC and plumbing. Heat pump installation, ductless mini-splits, water heater replacement, and emergency AC repair for the Research Triangle.",2400,["Heat pump","Mini-split","Water heater","Research Triangle"]),
  ("ct78","Carolina Home Services",["Interior","Exterior"],"Wilmington","North Carolina","NC",4.6,267,9,True,"Same day","$","Wilmington general contractor for coastal homes. Hurricane prep, rot repair, deck building, and interior remodels. We understand what the Carolina coast does to homes.",3100,["Hurricane prep","Rot repair","Coastal homes","Cape Fear region"]),

  # ── WASHINGTON (WA) – missing: Electrical, Exterior, Interior, Roof ──────────
  ("ct79","Pacific Northwest Roofing",["Roof","Exterior"],"Spokane","Washington","WA",4.8,256,16,True,"1-2 days","$$","Spokane roofing specialists for Eastern Washington's climate. Metal roofing, architectural shingles, and moss/lichen treatment for Pacific Northwest homes.",3200,["Metal roofing","Moss treatment","Snow load","Eastern WA"]),
  ("ct80","Seattle Electric Pros",["Electrical","Safety"],"Bellevue","Washington","WA",4.7,312,14,True,"< 3 hours","$$$","Bellevue and Eastside licensed electricians. EV charger installs, panel upgrades, smart home wiring, and ADU electrical for the greater Seattle metro.",2700,["EV charger","ADU electrical","Panel upgrade","Eastside Seattle"]),
  ("ct81","WA Home Renovations",["Interior","Exterior"],"Olympia","Washington","WA",4.6,198,8,True,"Same day","$$","Olympia general contractor. Deck building, bathroom remodels, kitchen updates, and weatherproofing for Washington's rainy climate.",2100,["Deck building","Weatherproofing","Kitchen remodel","South Puget Sound"]),

  # ── ILLINOIS (IL) – missing: Exterior, HVAC, Interior, Plumbing, Roof ────────
  ("ct82","Illinois HVAC Masters",["HVAC"],"Naperville","Illinois","IL",4.8,378,15,True,"< 2 hours","$$","Naperville and Chicagoland HVAC. Furnace replacement, AC installation, boiler service, and ductwork for Illinois winters and summers.",3800,["Furnace","Boiler","AC install","Chicagoland"]),
  ("ct83","Chicago Roofing Experts",["Roof","Exterior"],"Chicago","Illinois","IL",4.7,445,12,True,"Same day","$$","Chicago commercial and residential roofing. Flat roofs, asphalt shingles, and storm damage repair throughout Cook, DuPage, and Lake counties.",5400,["Flat roof","Storm damage","Cook County","Commercial ready"]),
  ("ct84","Prairie State Plumbing",["Plumbing"],"Rockford","Illinois","IL",4.6,256,13,True,"< 2 hours","$","Rockford plumbing specialists. Water heater replacement, drain cleaning, sewer camera inspection, and frozen pipe thawing for Northern Illinois winters.",2600,["Frozen pipe","Sewer camera","Water heater","Northern IL"]),
  ("ct85","Illinois Home Interiors",["Interior","Exterior"],"Peoria","Illinois","IL",4.5,312,7,True,"Same day","$","Peoria general contractor for kitchen and bath remodels, basement finishing, and deck construction. Central Illinois pricing with metro-quality workmanship.",3100,["Basement finish","Kitchen remodel","Deck building","Central IL"]),

  # ── COLORADO (CO) – missing: Exterior, Foundation, Interior, Roof ───────────
  ("ct86","Rocky Mountain Foundation",["Foundation"],"Fort Collins","Colorado","CO",4.8,178,20,True,"1-2 days","$$","Fort Collins foundation repair for Colorado's expansive clay and freeze-thaw conditions. Helical piers, wall anchors, and crawl space encapsulation.",2200,["Helical piers","Wall anchors","Freeze-thaw","Northern CO"]),
  ("ct87","Colorado Roofing Solutions",["Roof","Exterior"],"Colorado Springs","Colorado","CO",4.7,312,11,True,"Same day","$$","Colorado Springs roofing specialists. Hail damage experts — we document every impact for your insurance claim. Metal and impact-resistant shingles available.",3900,["Hail damage","Insurance claims","Impact-resistant","Front Range"]),
  ("ct88","Mile High Home Renovations",["Interior","Exterior"],"Boulder","Colorado","CO",4.6,234,8,True,"Same day","$$","Boulder general contractor for mountain-modern home renovations. Deck builds, bathroom upgrades, and energy efficiency improvements for Colorado homeowners.",2400,["Mountain modern","Energy efficiency","Deck building","Boulder area"]),

  # ── OHIO (OH) – missing: Electrical, Foundation, HVAC, Roof ────────────────
  ("ct89","Buckeye Foundation Repair",["Foundation"],"Cleveland","Ohio","OH",4.8,289,18,True,"1-2 days","$$","Cleveland foundation specialists for Ohio's freeze-thaw and clay soil conditions. Crack injection, pier systems, and basement waterproofing with transferable warranty.",3300,["Crack injection","Pier systems","Waterproofing","Northeast OH"]),
  ("ct90","Ohio HVAC Experts",["HVAC"],"Dayton","Ohio","OH",4.7,312,13,True,"< 2 hours","$$","Dayton heating and cooling specialists. Furnace replacement, heat pump installation, and 24/7 emergency HVAC repair throughout Southwest Ohio.",2800,["Furnace replacement","Heat pump","24/7","Southwest OH"]),
  ("ct91","Buckeye Electric",["Electrical","Safety"],"Akron","Ohio","OH",4.7,234,15,True,"< 3 hours","$$","Akron licensed electricians. Panel upgrades, whole-home rewiring, generator installs, and EV chargers throughout Northeast Ohio.",2400,["Panel upgrade","Rewiring","Generator","Northeast OH"]),
  ("ct92","Ohio Roofing Pros",["Roof","Exterior"],"Toledo","Ohio","OH",4.6,256,10,True,"Same day","$$","Toledo roofing and exterior specialists. Storm damage repair, asphalt and metal roofing, and siding replacement for Northwest Ohio homeowners.",3100,["Storm damage","Metal roofing","Siding","Northwest OH"]),

  # ── PENNSYLVANIA (PA) – missing: Electrical, Exterior, Foundation, Interior, Plumbing ──
  ("ct93","Keystone Foundation Repair",["Foundation"],"Allentown","Pennsylvania","PA",4.8,245,19,True,"1-2 days","$$","Allentown and Lehigh Valley foundation specialists. Bowing wall repair, waterproofing, and helical pier systems for Pennsylvania's old housing stock.",2700,["Bowing walls","Helical piers","Old housing","Lehigh Valley"]),
  ("ct94","PA Plumbing Masters",["Plumbing"],"Philadelphia","Pennsylvania","PA",4.7,389,14,True,"< 2 hours","$$$","Philadelphia plumbing for historic and modern homes. Water main replacement, sewer lateral repair, and emergency plumbing throughout Philly and surrounding counties.",4200,["Water main","Sewer lateral","Historic homes","Philadelphia"]),
  ("ct95","Pennsylvania Electric",["Electrical"],"Harrisburg","Pennsylvania","PA",4.7,198,12,True,"< 3 hours","$$","Harrisburg licensed electricians serving central PA. Panel replacements, whole-home rewiring, surge protection, and generator hookups.",1900,["Panel replacement","Rewiring","Generator hookup","Central PA"]),
  ("ct96","PA Home Services",["Interior","Exterior"],"Scranton","Pennsylvania","PA",4.5,267,9,True,"Same day","$","Scranton general contractor for kitchen and bath remodels, deck construction, and exterior siding. Northeastern Pennsylvania pricing with quality craftsmanship.",2600,["Kitchen remodel","Deck building","Siding","NEPA"]),

  # ── NEW YORK (NY) – missing: Exterior, Foundation, HVAC, Interior, Plumbing, Roof ──
  ("ct97","Empire State Foundation",["Foundation"],"Albany","New York","NY",4.8,234,21,True,"1-2 days","$$$","Albany foundation repair for Upstate New York's freeze-thaw cycles. Basement waterproofing, helical piers, and bowing wall systems with lifetime warranty.",2800,["Freeze-thaw","Helical piers","Bowing walls","Upstate NY"]),
  ("ct98","NY Plumbing Solutions",["Plumbing"],"Rochester","New York","NY",4.7,312,13,True,"< 2 hours","$$$","Rochester plumbing specialists. Frozen pipe emergencies, whole-house repiping, water heater replacement, and sewer line service for Upstate New York.",3100,["Frozen pipe","Repiping","Water heater","Rochester area"]),
  ("ct99","New York HVAC Masters",["HVAC"],"Syracuse","New York","NY",4.7,289,15,True,"< 2 hours","$$$","Syracuse heating and cooling for Central NY's harsh winters. Boiler replacement, heat pump installation, furnace service, and emergency heat calls.",2700,["Boiler","Heat pump","Emergency heat","Central NY"]),
  ("ct100","Upstate NY Roofing",["Roof","Exterior"],"Binghamton","New York","NY",4.6,198,11,True,"1-2 days","$$","Binghamton roofing and exterior for the Southern Tier. Ice dam experts, asphalt and metal roofing, and snow load engineering.",2200,["Ice dam","Snow load","Metal roofing","Southern Tier"]),
  ("ct101","NY Home Renovations",["Interior","Exterior"],"Yonkers","New York","NY",4.6,356,8,True,"Same day","$$$","Westchester County general contractor. Kitchen remodels, bathroom renovations, and finished basements for New York Metro suburban homeowners.",4100,["Kitchen remodel","Finished basement","Bathroom reno","Westchester"]),

  # ── VIRGINIA (VA) – missing: Electrical, Exterior, Foundation, Interior, Roof ─
  ("ct102","Virginia Foundation Experts",["Foundation"],"Norfolk","Virginia","VA",4.8,223,17,True,"1-2 days","$$","Norfolk and Hampton Roads foundation specialists. Saltwater soil challenges, pier systems, and crawl space waterproofing for coastal Virginia homes.",2600,["Coastal soil","Pier systems","Crawl space","Hampton Roads"]),
  ("ct103","Old Dominion Roofing",["Roof","Exterior"],"Virginia Beach","Virginia","VA",4.7,312,12,True,"Same day","$$","Virginia Beach roofing for coastal storms. Wind and storm damage specialists, metal roofing, and hurricane-rated installations for Hampton Roads homeowners.",3800,["Coastal storms","Hurricane-rated","Metal roofing","Hampton Roads"]),
  ("ct104","Virginia Electric Pros",["Electrical","Safety"],"Roanoke","Virginia","VA",4.7,198,14,True,"< 3 hours","$$","Roanoke licensed electricians for Western Virginia. Panel upgrades, generator installs, EV chargers, and smart home wiring.",1900,["Panel upgrade","Generator","EV charger","Western VA"]),
  ("ct105","Virginia Home Services",["Interior","Exterior"],"Alexandria","Virginia","VA",4.6,289,9,True,"Same day","$$$","Northern Virginia general contractor near DC. Kitchen and bath remodels, deck construction, and interior updates for the DMV market.",3400,["Kitchen remodel","Deck building","DMV area","NOVA"]),

  # ── TENNESSEE (TN) – missing: Electrical, Foundation, HVAC, Roof ────────────
  ("ct106","Tennessee Foundation Repair",["Foundation"],"Memphis","Tennessee","TN",4.8,267,20,True,"1-2 days","$$","Memphis and West Tennessee foundation specialists. Pier and beam, slab crack repair, and drainage solutions for Tennessee's clay-heavy soils.",2900,["Pier and beam","Slab repair","Clay soil","West TN"]),
  ("ct107","Tennessee HVAC Experts",["HVAC"],"Knoxville","Tennessee","TN",4.7,312,12,True,"< 2 hours","$$","Knoxville HVAC specialists for East Tennessee's varied climate. Heat pump installation, furnace replacement, and ductless mini-splits.",2600,["Heat pump","Mini-split","Furnace","East TN"]),
  ("ct108","Volunteer State Electric",["Electrical","Safety"],"Chattanooga","Tennessee","TN",4.7,234,13,True,"< 3 hours","$$","Chattanooga licensed electricians. Panel upgrades, generator hookups, EV charger installation, and whole-home surge protection.",2100,["Panel upgrade","Generator","EV charger","Chattanooga area"]),
  ("ct109","Tennessee Roofing Masters",["Roof","Exterior"],"Murfreesboro","Tennessee","TN",4.6,289,10,True,"Same day","$$","Murfreesboro roofing specialists. Storm and hail damage experts for Middle Tennessee. Architectural shingle, metal roofing, and free insurance consultation.",3300,["Storm damage","Hail","Insurance consultation","Middle TN"]),

  # ── MICHIGAN (MI) – missing: Exterior, Foundation, HVAC, Interior, Plumbing, Roof ──
  ("ct110","Michigan Foundation Repair",["Foundation"],"Grand Rapids","Michigan","MI",4.8,245,18,True,"1-2 days","$$","Grand Rapids foundation specialists for Michigan's freeze-thaw and clay conditions. Helical piers, waterproofing, and bowing wall repair with lifetime warranty.",2700,["Helical piers","Freeze-thaw","Bowing walls","West MI"]),
  ("ct111","Great Lakes HVAC",["HVAC"],"Lansing","Michigan","MI",4.7,289,14,True,"< 2 hours","$$","Lansing heating and cooling. Furnace replacement, heat pump installation, and 24/7 emergency HVAC repair throughout Mid-Michigan.",2400,["Furnace replacement","Heat pump","24/7 emergency","Mid-Michigan"]),
  ("ct112","Michigan Roofing Experts",["Roof","Exterior"],"Flint","Michigan","MI",4.6,223,11,True,"Same day","$$","Flint roofing and exterior. Asphalt and metal roofing, storm damage repair, and gutter installation for East Michigan homeowners.",2800,["Storm damage","Metal roofing","Gutters","East MI"]),
  ("ct113","Michigan Plumbing Pros",["Plumbing"],"Ann Arbor","Michigan","MI",4.7,312,10,True,"< 2 hours","$$","Ann Arbor plumbing specialists. Water heater replacement, sewer line service, frozen pipe emergencies, and whole-house repiping.",2600,["Water heater","Frozen pipe","Repiping","Ann Arbor area"]),
  ("ct114","Michigan Home Interiors",["Interior","Exterior"],"Kalamazoo","Michigan","MI",4.5,267,8,True,"Same day","$","Kalamazoo general contractor for kitchen and bath remodels, deck construction, and basement finishing throughout Southwest Michigan.",3100,["Kitchen remodel","Basement finish","Deck building","SW Michigan"]),

  # ── MINNESOTA (MN) – missing: Electrical, Exterior, Foundation, Interior, Plumbing, Roof ──
  ("ct115","Minnesota Foundation Repair",["Foundation"],"Rochester","Minnesota","MN",4.8,189,19,True,"1-2 days","$$","Rochester foundation specialists for Minnesota's extreme freeze-thaw. Basement waterproofing, helical pier systems, and egress window installation.",2300,["Freeze-thaw","Helical piers","Egress windows","Southeast MN"]),
  ("ct116","Minnesota Roofing Experts",["Roof","Exterior"],"Duluth","Minnesota","MN",4.7,234,14,True,"1-2 days","$$","Duluth roofing specialists. Metal and architectural roofing for Minnesota's harsh winters, ice dam prevention, and storm damage repair.",2700,["Ice dam","Metal roofing","Storm damage","Northern MN"]),
  ("ct117","Twin Cities Electric",["Electrical","Safety"],"St. Paul","Minnesota","MN",4.7,312,12,True,"< 3 hours","$$","St. Paul licensed electricians. Panel upgrades, generator installs, EV chargers, and knob-and-tube replacement for Twin Cities homeowners.",2900,["Panel upgrade","Generator","K&T replacement","Twin Cities"]),
  ("ct118","MN Plumbing Solutions",["Plumbing"],"Bloomington","Minnesota","MN",4.6,256,11,True,"< 2 hours","$$","Bloomington plumbing for the Twin Cities suburbs. Frozen pipe emergencies, water heater replacement, and whole-house repiping.",2400,["Frozen pipe","Water heater","Repiping","Twin Cities suburbs"]),
  ("ct119","Minnesota Home Services",["Interior","Exterior"],"St. Cloud","Minnesota","MN",4.5,198,7,True,"Same day","$","St. Cloud general contractor for kitchen and bath remodels, deck construction, and three-season porch additions throughout Central Minnesota.",2100,["Three-season porch","Kitchen remodel","Deck building","Central MN"]),

  # ── WISCONSIN (WI) – missing: Exterior, Foundation, HVAC, Interior, Plumbing, Roof ──
  ("ct120","Wisconsin Foundation Repair",["Foundation"],"Green Bay","Wisconsin","WI",4.8,198,17,True,"1-2 days","$$","Green Bay foundation specialists. Basement waterproofing, helical piers, and crack repair for Wisconsin's freeze-thaw and clay conditions.",2200,["Helical piers","Waterproofing","Freeze-thaw","Northeast WI"]),
  ("ct121","Badger State HVAC",["HVAC"],"Madison","Wisconsin","WI",4.7,267,12,True,"< 2 hours","$$","Madison heating and cooling. Furnace replacement, AC installation, and heat pump systems for Wisconsin's four-season climate.",2600,["Furnace","AC install","Heat pump","Madison area"]),
  ("ct122","Wisconsin Roofing Pros",["Roof","Exterior"],"Racine","Wisconsin","WI",4.6,234,10,True,"Same day","$$","Racine roofing and exterior. Asphalt and metal roofing, storm damage repair, and gutter installation throughout Southeast Wisconsin.",2700,["Storm damage","Metal roofing","Gutters","SE Wisconsin"]),
  ("ct123","Wisconsin Plumbing Masters",["Plumbing"],"Appleton","Wisconsin","WI",4.6,223,11,True,"< 2 hours","$$","Appleton plumbing specialists. Water heater replacement, drain cleaning, frozen pipe emergencies, and sewer line service for Northeast Wisconsin.",2300,["Water heater","Drain cleaning","Frozen pipe","NE Wisconsin"]),
  ("ct124","WI Home Renovations",["Interior","Exterior"],"Waukesha","Wisconsin","WI",4.5,189,8,True,"Same day","$","Waukesha general contractor for kitchen and bath remodels, deck construction, and basement finishing throughout Southeast Wisconsin.",2100,["Kitchen remodel","Basement finish","Deck building","SE Wisconsin"]),

  # ── MISSOURI (MO) – missing: Electrical, Exterior, Foundation, Interior, Plumbing, Roof ──
  ("ct125","Missouri Foundation Repair",["Foundation"],"Kansas City","Missouri","MO",4.8,234,18,True,"1-2 days","$$","Kansas City foundation specialists. Pier and beam leveling, slab crack repair, and basement waterproofing for Missouri's clay-heavy soils.",2600,["Pier and beam","Slab repair","Clay soil","KC metro"]),
  ("ct126","Show-Me State Roofing",["Roof","Exterior"],"Springfield","Missouri","MO",4.7,267,11,True,"Same day","$$","Springfield roofing specialists. Hail and storm damage experts throughout the Ozarks. Free insurance consultation and fast estimates.",3100,["Hail damage","Storm damage","Insurance","Ozarks"]),
  ("ct127","Missouri Electric Pros",["Electrical","Safety"],"Columbia","Missouri","MO",4.7,198,13,True,"< 3 hours","$$","Columbia licensed electricians for Mid-Missouri. Panel upgrades, generator hookups, EV chargers, and whole-home surge protection.",1900,["Panel upgrade","Generator","EV charger","Mid-Missouri"]),
  ("ct128","MO Plumbing Solutions",["Plumbing"],"Independence","Missouri","MO",4.6,223,10,True,"< 2 hours","$$","Independence plumbing for the Kansas City metro. Water heater replacement, drain cleaning, and emergency plumbing service.",2200,["Water heater","Drain cleaning","Emergency","KC metro"]),
  ("ct129","Missouri Home Services",["Interior","Exterior"],"Jefferson City","Missouri","MO",4.5,178,7,True,"Same day","$","Jefferson City general contractor for kitchen and bath remodels, deck construction, and basement finishing throughout Central Missouri.",1900,["Kitchen remodel","Deck building","Basement finish","Central MO"]),

  # ── INDIANA (IN) – missing: Electrical, Foundation, HVAC, Roof ──────────────
  ("ct130","Hoosier Foundation Repair",["Foundation"],"Fort Wayne","Indiana","IN",4.8,198,19,True,"1-2 days","$$","Fort Wayne foundation specialists. Basement waterproofing, helical piers, and bowing wall repair for Northeast Indiana homeowners.",2300,["Helical piers","Waterproofing","Bowing walls","NE Indiana"]),
  ("ct131","Indiana HVAC Masters",["HVAC"],"South Bend","Indiana","IN",4.7,256,12,True,"< 2 hours","$$","South Bend heating and cooling. Furnace replacement, heat pump installation, and emergency HVAC repair for Northwest Indiana.",2400,["Furnace","Heat pump","Emergency repair","NW Indiana"]),
  ("ct132","Indiana Electric Solutions",["Electrical","Safety"],"Bloomington","Indiana","IN",4.6,189,11,True,"< 3 hours","$$","Bloomington licensed electricians for South-Central Indiana. Panel upgrades, generator installs, and EV charger installation.",1800,["Panel upgrade","Generator","EV charger","South-Central IN"]),
  ("ct133","Hoosier Roofing Experts",["Roof","Exterior"],"Evansville","Indiana","IN",4.6,234,10,True,"Same day","$$","Evansville roofing and exterior for Southwest Indiana. Storm damage repair, architectural shingle, and metal roofing specialists.",2600,["Storm damage","Metal roofing","SW Indiana","Insurance claims"]),

  # ── LOUISIANA (LA) – missing: Electrical, Exterior, HVAC, Interior, Roof ─────
  ("ct134","Pelican State HVAC",["HVAC"],"Baton Rouge","Louisiana","LA",4.8,312,14,True,"< 1 hour","$$","Baton Rouge HVAC specialists for Louisiana's extreme humidity and heat. AC replacement, duct cleaning, and 24/7 emergency cooling service.",3800,["Extreme humidity","AC replacement","Duct cleaning","24/7"]),
  ("ct135","Louisiana Roofing Pros",["Roof","Exterior"],"Shreveport","Louisiana","LA",4.7,267,12,True,"Same day","$$","Shreveport roofing specialists. Hurricane and storm damage repair, metal roofing, and wind-rated installations throughout Northwest Louisiana.",3100,["Hurricane damage","Metal roofing","Wind-rated","NW Louisiana"]),
  ("ct136","Bayou Electric",["Electrical","Safety"],"Metairie","Louisiana","LA",4.7,223,15,True,"< 3 hours","$$","Metairie and Greater New Orleans licensed electricians. Flood-damage rewiring, panel upgrades, and GFCI installation for Louisiana's wet climate.",2100,["Flood rewiring","GFCI","Panel upgrade","Greater NOLA"]),
  ("ct137","Louisiana Home Services",["Interior","Exterior"],"Lake Charles","Louisiana","LA",4.5,198,7,True,"Same day","$","Lake Charles general contractor for storm restoration, kitchen remodels, and exterior repairs. Experts in hurricane damage restoration for Southwest Louisiana.",2400,["Hurricane restoration","Kitchen remodel","Storm repair","SW Louisiana"]),

  # ── SOUTH CAROLINA (SC) – missing: Electrical, Foundation, HVAC, Interior, Plumbing ──
  ("ct138","Palmetto Foundation Experts",["Foundation"],"Columbia","South Carolina","SC",4.8,212,17,True,"1-2 days","$$","Columbia foundation and crawl space specialists. Pier and beam repair, encapsulation, and drainage solutions for South Carolina's clay-heavy soils.",2500,["Pier and beam","Crawl space","Clay soil","Midlands SC"]),
  ("ct139","South Carolina HVAC",["HVAC"],"Myrtle Beach","South Carolina","SC",4.7,289,11,True,"< 2 hours","$$","Myrtle Beach HVAC specialists for coastal South Carolina's humidity. AC replacement, duct cleaning, and dehumidification systems.",3200,["Coastal humidity","AC replacement","Dehumidification","Grand Strand"]),
  ("ct140","SC Electric Solutions",["Electrical","Safety"],"Greenville","South Carolina","SC",4.7,234,13,True,"< 3 hours","$$","Greenville Upstate South Carolina electricians. Panel upgrades, EV charger installs, generator hookups, and whole-home surge protection.",2200,["Panel upgrade","EV charger","Generator","Upstate SC"]),
  ("ct141","Carolina Plumbing Masters",["Plumbing"],"Spartanburg","South Carolina","SC",4.6,198,10,True,"< 2 hours","$$","Spartanburg plumbing for the Upstate. Water heater replacement, drain cleaning, sewer line service, and emergency plumbing.",2100,["Water heater","Drain cleaning","Sewer line","Upstate SC"]),
  ("ct142","SC Home Renovations",["Interior","Exterior"],"Rock Hill","South Carolina","SC",4.5,178,7,True,"Same day","$","Rock Hill general contractor near Charlotte. Kitchen and bath remodels, deck construction, and exterior updates for Upstate South Carolina homeowners.",1900,["Kitchen remodel","Deck building","Charlotte adjacent","Upstate SC"]),

  # ── IOWA (IA) – missing: Electrical, Foundation, Plumbing, Roof ─────────────
  ("ct143","Iowa Foundation Repair",["Foundation"],"Cedar Rapids","Iowa","IA",4.8,178,18,True,"1-2 days","$$","Cedar Rapids foundation specialists for Iowa's freeze-thaw and loess soil. Basement waterproofing, wall anchors, and helical pier systems.",2200,["Freeze-thaw","Wall anchors","Loess soil","Eastern IA"]),
  ("ct144","Iowa Roofing Experts",["Roof","Exterior"],"Davenport","Iowa","IA",4.7,212,11,True,"Same day","$$","Davenport roofing and exterior. Hail and storm damage specialists throughout the Quad Cities. Free insurance consultation.",2500,["Hail damage","Storm damage","Insurance","Quad Cities"]),
  ("ct145","Iowa Electric Pros",["Electrical","Safety"],"Waterloo","Iowa","IA",4.6,178,12,True,"< 3 hours","$$","Waterloo licensed electricians for Northeast Iowa. Panel upgrades, generator installs, EV chargers, and electrical troubleshooting.",1800,["Panel upgrade","Generator","EV charger","NE Iowa"]),
  ("ct146","Iowa Plumbing Solutions",["Plumbing"],"Sioux City","Iowa","IA",4.6,198,10,True,"< 2 hours","$$","Sioux City plumbing for Western Iowa. Water heater replacement, drain cleaning, frozen pipe emergencies, and sewer line service.",2100,["Water heater","Frozen pipe","Sewer line","Western IA"]),

  # ── KANSAS (KS) – missing: Electrical, Exterior, Foundation, HVAC, Roof ──────
  ("ct147","Sunflower Foundation Repair",["Foundation"],"Overland Park","Kansas","KS",4.8,189,19,True,"1-2 days","$$","Overland Park foundation specialists for Kansas's expansive clay and tornado-stress damage. Pier and beam, slab crack repair, and waterproofing.",2300,["Expansive clay","Tornado damage","Pier and beam","KC Kansas"]),
  ("ct148","Kansas HVAC Experts",["HVAC"],"Topeka","Kansas","KS",4.7,223,12,True,"< 2 hours","$$","Topeka heating and cooling for Central Kansas. Furnace replacement, AC installation, and emergency HVAC repair throughout the Flint Hills region.",2400,["Furnace","AC install","Emergency repair","Central KS"]),
  ("ct149","Kansas Electric Masters",["Electrical","Safety"],"Manhattan","Kansas","KS",4.6,167,13,True,"< 3 hours","$$","Manhattan Kansas licensed electricians. Panel upgrades, generator hookups, EV chargers, and storm-damage electrical repair.",1700,["Panel upgrade","Generator","Storm damage","NE Kansas"]),
  ("ct150","Wheat State Roofing",["Roof","Exterior"],"Lawrence","Kansas","KS",4.6,198,10,True,"Same day","$$","Lawrence roofing specialists. Hail and tornado damage experts for Northeast Kansas. Free insurance consultation and next-day estimates.",2300,["Hail damage","Tornado damage","Insurance","NE Kansas"]),

  # ── KENTUCKY (KY) – missing: Electrical, Exterior, Foundation, Interior, Roof ─
  ("ct151","Kentucky Foundation Repair",["Foundation"],"Lexington","Kentucky","KY",4.8,212,18,True,"1-2 days","$$","Lexington foundation specialists for Kentucky's limestone-karst terrain. Sinkhole assessment, pier systems, and basement waterproofing.",2500,["Sinkhole","Limestone karst","Pier systems","Central KY"]),
  ("ct152","Bluegrass Roofing",["Roof","Exterior"],"Bowling Green","Kentucky","KY",4.7,245,11,True,"Same day","$$","Bowling Green roofing and exterior for South-Central Kentucky. Hail and storm damage experts, architectural shingle and metal roofing.",2800,["Hail damage","Storm damage","Metal roofing","S-Central KY"]),
  ("ct153","Kentucky Electric Solutions",["Electrical","Safety"],"Owensboro","Kentucky","KY",4.6,178,13,True,"< 3 hours","$$","Owensboro licensed electricians for Western Kentucky. Panel upgrades, generator hookups, EV chargers, and residential rewiring.",1800,["Panel upgrade","Generator","Rewiring","Western KY"]),
  ("ct154","KY Home Renovations",["Interior","Exterior"],"Covington","Kentucky","KY",4.5,189,7,True,"Same day","$","Covington general contractor near Cincinnati. Kitchen and bath remodels, deck construction, and basement finishing for Northern Kentucky homeowners.",2100,["Kitchen remodel","Deck building","Cincinnati adjacent","Northern KY"]),

  # ── MISSISSIPPI (MS) – missing: Electrical, Foundation, HVAC, Interior, Plumbing ──
  ("ct155","Mississippi Foundation Repair",["Foundation"],"Hattiesburg","Mississippi","MS",4.8,178,19,True,"1-2 days","$$","Hattiesburg foundation specialists for Mississippi's clay soil and flood-prone terrain. Pier and beam, underpinning, and drainage solutions.",2100,["Clay soil","Flood terrain","Pier and beam","S Mississippi"]),
  ("ct156","Magnolia State HVAC",["HVAC"],"Biloxi","Mississippi","MS",4.7,234,12,True,"< 2 hours","$$","Biloxi coastal HVAC specialists. AC replacement and maintenance for Mississippi's Gulf Coast heat and humidity. 24/7 emergency cooling.",2800,["Gulf Coast","AC replacement","24/7","Coastal MS"]),
  ("ct157","Mississippi Electric Pros",["Electrical","Safety"],"Tupelo","Mississippi","MS",4.6,178,13,True,"< 3 hours","$$","Tupelo licensed electricians for North Mississippi. Panel upgrades, generator installs, EV chargers, and electrical troubleshooting.",1700,["Panel upgrade","Generator","EV charger","N Mississippi"]),
  ("ct158","MS Plumbing Masters",["Plumbing"],"Gulfport","Mississippi","MS",4.6,198,10,True,"< 2 hours","$$","Gulfport plumbing for the Gulf Coast. Water heater replacement, drain cleaning, and slab leak detection throughout Coastal Mississippi.",2200,["Slab leak","Water heater","Drain cleaning","Gulf Coast MS"]),
  ("ct159","Mississippi Home Services",["Interior","Exterior"],"Meridian","Mississippi","MS",4.5,167,7,True,"Same day","$","Meridian general contractor for kitchen and bath remodels, deck construction, and exterior updates throughout East-Central Mississippi.",1800,["Kitchen remodel","Deck building","Exterior","E-Central MS"]),

  # ── ALABAMA (AL) – missing: Electrical, Exterior, Foundation, Interior, Roof ─
  ("ct160","Alabama Foundation Repair",["Foundation"],"Huntsville","Alabama","AL",4.8,198,18,True,"1-2 days","$$","Huntsville foundation specialists. Pier and beam, slab crack repair, and crawl space encapsulation for North Alabama's clay and karst terrain.",2300,["Pier and beam","Slab repair","Crawl space","N Alabama"]),
  ("ct161","Yellowhammer Roofing",["Roof","Exterior"],"Mobile","Alabama","AL",4.7,256,12,True,"Same day","$$","Mobile roofing and exterior for Coastal Alabama. Hurricane and storm damage specialists, metal roofing, and wind-rated systems for Gulf Coast homeowners.",3100,["Hurricane damage","Metal roofing","Wind-rated","Coastal AL"]),
  ("ct162","Alabama Electric Masters",["Electrical","Safety"],"Montgomery","Alabama","AL",4.7,212,14,True,"< 3 hours","$$","Montgomery licensed electricians for Central Alabama. Panel upgrades, generator installs, and EV charger installation throughout the River Region.",2000,["Panel upgrade","Generator","EV charger","River Region"]),
  ("ct163","Alabama Home Renovations",["Interior","Exterior"],"Auburn","Alabama","AL",4.5,189,7,True,"Same day","$","Auburn general contractor for kitchen and bath remodels, deck building, and exterior updates throughout East Alabama and the Wiregrass region.",2100,["Kitchen remodel","Deck building","Exterior","E Alabama"]),

  # ── ARKANSAS (AR) – missing: Exterior, Foundation, HVAC, Interior, Plumbing, Roof ──
  ("ct164","Natural State Foundation",["Foundation"],"Fort Smith","Arkansas","AR",4.8,167,19,True,"1-2 days","$$","Fort Smith foundation specialists for Western Arkansas's clay and karst conditions. Pier and beam, slab repair, and drainage solutions.",2000,["Pier and beam","Karst","Clay soil","W Arkansas"]),
  ("ct165","Arkansas HVAC Masters",["HVAC"],"Fayetteville","Arkansas","AR",4.7,212,11,True,"< 2 hours","$$","Fayetteville heating and cooling for Northwest Arkansas. Heat pump installation, furnace replacement, and mini-split systems for the growing NWA market.",2400,["Heat pump","Mini-split","Furnace","NW Arkansas"]),
  ("ct166","Arkansas Roofing Experts",["Roof","Exterior"],"Jonesboro","Arkansas","AR",4.7,189,10,True,"Same day","$$","Jonesboro roofing for Northeast Arkansas. Storm and hail damage specialists with insurance consultation and free inspection.",2200,["Storm damage","Hail","Insurance","NE Arkansas"]),
  ("ct167","Natural State Plumbing",["Plumbing"],"Springdale","Arkansas","AR",4.6,178,10,True,"< 2 hours","$$","Springdale plumbing for Northwest Arkansas. Water heater replacement, drain cleaning, and emergency plumbing throughout the NWA metro.",2000,["Water heater","Drain cleaning","Emergency","NWA metro"]),
  ("ct168","AR Home Services",["Interior","Exterior"],"Conway","Arkansas","AR",4.5,167,7,True,"Same day","$","Conway general contractor for kitchen and bath remodels, deck construction, and exterior updates throughout Central Arkansas.",1800,["Kitchen remodel","Deck building","Exterior","Central AR"]),

  # ── NEVADA (NV) – missing: Electrical, Exterior, Foundation, Interior, Roof ──
  ("ct169","Nevada Foundation Repair",["Foundation"],"Reno","Nevada","NV",4.8,189,17,True,"1-2 days","$$","Reno foundation specialists for Northern Nevada's desert soil and seismic activity. Concrete leveling, helical piers, and crack injection.",2200,["Desert soil","Seismic","Helical piers","Northern NV"]),
  ("ct170","Silver State Roofing",["Roof","Exterior"],"Henderson","Nevada","NV",4.7,234,11,True,"Same day","$$","Henderson roofing for the Las Vegas Valley. Cool roof systems, tile roofing, and flat roof specialists for Nevada's desert sun conditions.",2600,["Cool roof","Tile roofing","Desert sun","Las Vegas Valley"]),
  ("ct171","Nevada Electric Pros",["Electrical","Safety"],"North Las Vegas","Nevada","NV",4.7,267,13,True,"< 3 hours","$$","North Las Vegas licensed electricians. Solar battery systems, panel upgrades, EV chargers, and smart home wiring for Nevada homeowners.",2400,["Solar battery","EV charger","Panel upgrade","Las Vegas metro"]),
  ("ct172","Nevada Home Services",["Interior","Exterior"],"Sparks","Nevada","NV",4.5,189,7,True,"Same day","$$","Sparks general contractor near Reno. Kitchen and bath remodels, patio covers, and exterior updates for Northern Nevada homeowners.",2000,["Kitchen remodel","Patio cover","Exterior","Reno area"]),

  # ── UTAH (UT) – missing: Electrical, Foundation, HVAC, Interior, Plumbing ────
  ("ct173","Utah Foundation Repair",["Foundation"],"Provo","Utah","UT",4.8,198,18,True,"1-2 days","$$","Provo foundation specialists for Utah County's expansive soil and seismic zone. Helical piers, slab leveling, and basement waterproofing.",2300,["Expansive soil","Seismic zone","Helical piers","Utah County"]),
  ("ct174","Beehive State HVAC",["HVAC"],"Ogden","Utah","UT",4.7,234,12,True,"< 2 hours","$$","Ogden heating and cooling for Northern Utah. Heat pump installation, furnace replacement, and swamp cooler conversion for Utah's climate.",2400,["Heat pump","Swamp cooler","Furnace","Northern UT"]),
  ("ct175","Utah Electric Masters",["Electrical","Safety"],"St. George","Utah","UT",4.7,189,13,True,"< 3 hours","$$","St. George licensed electricians for Southern Utah. Solar panel wiring, panel upgrades, EV chargers, and smart home systems.",1900,["Solar wiring","EV charger","Panel upgrade","Southern UT"]),
  ("ct176","Utah Plumbing Experts",["Plumbing"],"West Jordan","Utah","UT",4.6,223,10,True,"< 2 hours","$$","West Jordan plumbing for the Salt Lake Valley. Water heater replacement, drain cleaning, and sewer line service.",2200,["Water heater","Drain cleaning","Sewer line","Salt Lake Valley"]),
  ("ct177","Utah Home Renovations",["Interior","Exterior"],"Murray","Utah","UT",4.5,189,7,True,"Same day","$$","Murray general contractor for the Salt Lake metro. Kitchen and bath remodels, deck construction, and basement finishing throughout Utah's Wasatch Front.",2000,["Kitchen remodel","Deck building","Basement finish","Wasatch Front"]),

  # ── OREGON (OR) – missing: Exterior, Foundation, Interior, Plumbing, Roof ────
  ("ct178","Oregon Foundation Repair",["Foundation"],"Salem","Oregon","OR",4.8,212,18,True,"1-2 days","$$","Salem foundation specialists for the Willamette Valley's clay-heavy soils and wet winters. Helical piers, drainage solutions, and crawl space encapsulation.",2400,["Willamette Valley","Clay soil","Helical piers","Mid-Willamette"]),
  ("ct179","Oregon Roofing Masters",["Roof","Exterior"],"Eugene","Oregon","OR",4.7,256,12,True,"1-2 days","$$","Eugene roofing specialists for Western Oregon's rainy climate. Moss prevention, standing seam metal, and architectural shingle for PNW homes.",2800,["Moss prevention","Metal roofing","PNW climate","Willamette Valley"]),
  ("ct180","Oregon Plumbing Pros",["Plumbing"],"Bend","Oregon","OR",4.7,198,11,True,"< 2 hours","$$","Bend plumbing for Central Oregon. Water heater replacement, tankless systems, and irrigation winterization for high desert conditions.",2100,["Water heater","Tankless","Winterization","Central OR"]),
  ("ct181","Oregon Home Services",["Interior","Exterior"],"Medford","Oregon","OR",4.5,178,7,True,"Same day","$","Medford general contractor for Southern Oregon. Kitchen and bath remodels, deck construction, and wildfire defensible space improvements.",1900,["Kitchen remodel","Deck building","Wildfire prep","Southern OR"]),

  # ── NEW MEXICO (NM) – missing: Exterior, Foundation, Interior, Plumbing, Roof ─
  ("ct182","New Mexico Foundation Repair",["Foundation"],"Santa Fe","New Mexico","NM",4.8,167,20,True,"1-2 days","$$","Santa Fe foundation specialists for New Mexico's caliche and adobe soil challenges. Concrete leveling, pier installation, and adobe repair.",1900,["Caliche","Adobe repair","Concrete leveling","N New Mexico"]),
  ("ct183","Land of Enchantment Roofing",["Roof","Exterior"],"Las Cruces","New Mexico","NM",4.7,198,11,True,"Same day","$$","Las Cruces roofing for Southern New Mexico. Flat roof systems, cool roofs, and storm damage repair for desert conditions.",2200,["Flat roof","Cool roof","Desert climate","S New Mexico"]),
  ("ct184","NM Plumbing Experts",["Plumbing"],"Rio Rancho","New Mexico","NM",4.6,178,10,True,"< 2 hours","$$","Rio Rancho plumbing for the Albuquerque metro. Water softener installation, water heater replacement, and evaporative cooler plumbing.",2000,["Water softener","Evaporative cooler","Water heater","ABQ metro"]),
  ("ct185","New Mexico Home Services",["Interior","Exterior"],"Farmington","New Mexico","NM",4.5,167,7,True,"Same day","$","Farmington general contractor for Northwest New Mexico. Kitchen and bath remodels, deck construction, and exterior stucco repair.",1800,["Kitchen remodel","Stucco repair","Deck building","NW New Mexico"]),

  # ── CONNECTICUT (CT) – missing: Electrical, Foundation, HVAC, Interior, Plumbing ──
  ("ct186","Connecticut Foundation Repair",["Foundation"],"Bridgeport","Connecticut","CT",4.8,234,19,True,"1-2 days","$$$","Bridgeport foundation specialists for New England's freeze-thaw and glacial till soils. Helical piers, waterproofing, and bowing wall repair.",2700,["Glacial till","Helical piers","Bowing walls","SW Connecticut"]),
  ("ct187","CT HVAC Experts",["HVAC"],"Stamford","Connecticut","CT",4.8,267,13,True,"< 2 hours","$$$","Stamford heating and cooling for Fairfield County. High-efficiency heat pump installation, oil-to-heat-pump conversions, and ductless mini-splits.",2600,["Heat pump","Oil conversion","Mini-split","Fairfield County"]),
  ("ct188","Connecticut Electric Pros",["Electrical","Safety"],"New Haven","Connecticut","CT",4.7,245,14,True,"< 3 hours","$$$","New Haven licensed electricians. Panel upgrades, EV charger installs, knob-and-tube replacement, and generator hookups for Connecticut homeowners.",2400,["Panel upgrade","EV charger","K&T replacement","New Haven area"]),
  ("ct189","CT Plumbing Masters",["Plumbing"],"Waterbury","Connecticut","CT",4.7,212,12,True,"< 2 hours","$$$","Waterbury plumbing for Central Connecticut. Water heater replacement, pipe insulation, and frozen pipe emergencies for New England winters.",2100,["Water heater","Frozen pipe","Pipe insulation","Central CT"]),
  ("ct190","Connecticut Home Renovations",["Interior","Exterior"],"Norwalk","Connecticut","CT",4.6,223,8,True,"Same day","$$$","Norwalk general contractor for Fairfield County. Kitchen and bath remodels, deck construction, and basement finishing near New York City.",2400,["Kitchen remodel","Deck building","Basement finish","Fairfield County"]),

  # ── NEBRASKA (NE) – missing: Electrical, Exterior, Foundation, Interior, Roof ─
  ("ct191","Nebraska Foundation Repair",["Foundation"],"Lincoln","Nebraska","NE",4.8,178,18,True,"1-2 days","$$","Lincoln foundation specialists for Nebraska's clay-heavy soil and freeze-thaw cycles. Basement waterproofing, helical piers, and wall anchor systems.",2100,["Clay soil","Helical piers","Wall anchors","SE Nebraska"]),
  ("ct192","Cornhusker Roofing",["Roof","Exterior"],"Bellevue","Nebraska","NE",4.7,198,11,True,"Same day","$$","Bellevue roofing and exterior for the Omaha metro. Hail and tornado damage specialists. We handle the full insurance claim process.",2300,["Hail damage","Tornado","Insurance","Omaha metro"]),
  ("ct193","Nebraska Electric Masters",["Electrical","Safety"],"Grand Island","Nebraska","NE",4.6,167,12,True,"< 3 hours","$$","Grand Island licensed electricians for Central Nebraska. Panel upgrades, generator hookups, EV chargers, and storm damage electrical repair.",1700,["Panel upgrade","Generator","EV charger","Central NE"]),
  ("ct194","NE Home Services",["Interior","Exterior"],"Kearney","Nebraska","NE",4.5,156,7,True,"Same day","$","Kearney general contractor for Central Nebraska. Kitchen and bath remodels, deck construction, and exterior updates throughout the Platte Valley.",1700,["Kitchen remodel","Deck building","Exterior","Platte Valley"]),

  # ── IDAHO (ID) – missing: Exterior, Foundation, Interior, Plumbing, Roof ─────
  ("ct195","Idaho Foundation Repair",["Foundation"],"Meridian","Idaho","ID",4.8,178,17,True,"1-2 days","$$","Meridian foundation specialists for the Treasure Valley's clay soil and seismic activity. Helical piers, concrete leveling, and crawl space encapsulation.",2000,["Treasure Valley","Clay soil","Helical piers","Treasure Valley"]),
  ("ct196","Gem State Roofing",["Roof","Exterior"],"Nampa","Idaho","ID",4.7,189,11,True,"Same day","$$","Nampa roofing and exterior for Southwest Idaho. Wind and storm damage repair, metal roofing, and flat roof systems for Treasure Valley homeowners.",2200,["Storm damage","Metal roofing","Flat roof","SW Idaho"]),
  ("ct197","Idaho Plumbing Pros",["Plumbing"],"Idaho Falls","Idaho","ID",4.6,167,10,True,"< 2 hours","$$","Idaho Falls plumbing for Eastern Idaho. Water heater replacement, irrigation winterization, and frozen pipe emergencies for high desert winters.",1900,["Water heater","Winterization","Frozen pipe","E Idaho"]),
  ("ct198","Idaho Home Services",["Interior","Exterior"],"Caldwell","Idaho","ID",4.5,156,7,True,"Same day","$","Caldwell general contractor for the Treasure Valley. Kitchen and bath remodels, deck construction, and exterior updates throughout Southwest Idaho.",1800,["Kitchen remodel","Deck building","Exterior","SW Idaho"]),

  # ── HAWAII (HI) – missing: Electrical, Foundation, HVAC, Roof ───────────────
  ("ct199","Hawaii Foundation Repair",["Foundation"],"Hilo","Hawaii","HI",4.8,156,18,True,"1-2 days","$$$","Hilo foundation specialists for Hawaii's volcanic soil and wet conditions. Pier installation, slab repair, and moisture control for Big Island homes.",1900,["Volcanic soil","Moisture control","Pier installation","Big Island"]),
  ("ct200","Pacific Island HVAC",["HVAC"],"Kahului","Hawaii","HI",4.8,198,13,True,"< 2 hours","$$$","Maui HVAC specialists for Hawaii's tropical climate. Ductless mini-splits, whole-house dehumidification, and AC maintenance for island homeowners.",2200,["Tropical climate","Mini-split","Dehumidification","Maui"]),
  ("ct201","Hawaii Electric Pros",["Electrical","Safety"],"Pearl City","Hawaii","HI",4.7,223,14,True,"< 3 hours","$$$","Oahu licensed electricians. Solar panel wiring, EV charger installation, generator hookups, and smart home systems for Hawaii's high electricity rates.",2100,["Solar wiring","EV charger","Generator","Oahu"]),
  ("ct202","Hawaii Roofing Experts",["Roof","Exterior"],"Kailua","Hawaii","HI",4.7,178,11,True,"1-2 days","$$$","Kailua roofing specialists for Oahu's tropical storms and salt air. Metal and cool roof systems, hurricane strapping, and wind-rated installations.",1900,["Hurricane strapping","Metal roofing","Salt air","Oahu"]),

  # ── MONTANA (MT) – missing: Electrical, Foundation, Interior, Plumbing ────────
  ("ct203","Montana Foundation Repair",["Foundation"],"Missoula","Montana","MT",4.8,145,20,True,"1-2 days","$$","Missoula foundation specialists for Western Montana's rocky terrain and freeze-thaw conditions. Crawl space encapsulation, drainage solutions, and pier installation.",1700,["Rocky terrain","Freeze-thaw","Crawl space","W Montana"]),
  ("ct204","Montana Electric Masters",["Electrical","Safety"],"Great Falls","Montana","MT",4.7,156,13,True,"< 3 hours","$$","Great Falls licensed electricians for Central Montana. Panel upgrades, generator hookups, wood stove wiring, and EV charger installation.",1600,["Panel upgrade","Generator","Wood stove","Central MT"]),
  ("ct205","Montana Plumbing Solutions",["Plumbing"],"Kalispell","Montana","MT",4.6,145,11,True,"< 2 hours","$$","Kalispell plumbing for the Flathead Valley. Water heater replacement, pipe winterization, and frozen pipe emergencies for Northwest Montana winters.",1700,["Frozen pipe","Winterization","Water heater","Flathead Valley"]),
  ("ct206","Montana Home Services",["Interior","Exterior"],"Bozeman","Montana","MT",4.6,167,8,True,"Same day","$$","Bozeman general contractor for mountain homes. Kitchen and bath remodels, deck construction, and log home chinking and maintenance.",1900,["Log home","Kitchen remodel","Deck building","SW Montana"]),

  # ── NEW HAMPSHIRE (NH) – missing: Electrical, Exterior, Foundation, Interior, Roof ──
  ("ct207","Granite State Foundation",["Foundation"],"Nashua","New Hampshire","NH",4.8,189,18,True,"1-2 days","$$","Nashua foundation specialists for Southern New Hampshire's glacial till and freeze-thaw. Helical piers, waterproofing, and bowing wall repair.",2200,["Glacial till","Helical piers","Freeze-thaw","S New Hampshire"]),
  ("ct208","NH Roofing Experts",["Roof","Exterior"],"Concord","New Hampshire","NH",4.7,212,12,True,"1-2 days","$$","Concord roofing for New Hampshire's harsh winters. Ice dam specialists, metal roofing, and architectural shingle installation with proper ventilation.",2400,["Ice dam","Metal roofing","Ventilation","Central NH"]),
  ("ct209","New Hampshire Electric",["Electrical","Safety"],"Dover","New Hampshire","NH",4.7,189,13,True,"< 3 hours","$$","Dover licensed electricians for Seacoast New Hampshire. Panel upgrades, generator hookups, EV chargers, and smart home wiring.",1900,["Panel upgrade","Generator","EV charger","Seacoast NH"]),
  ("ct210","NH Home Renovations",["Interior","Exterior"],"Keene","New Hampshire","NH",4.5,167,7,True,"Same day","$$","Keene general contractor for Southwest New Hampshire. Kitchen and bath remodels, deck construction, and three-season porch additions.",1800,["Kitchen remodel","Three-season porch","Deck building","SW New Hampshire"]),

  # ── DELAWARE (DE) – missing: Exterior, Foundation, HVAC, Interior, Roof ──────
  ("ct211","Delaware Foundation Repair",["Foundation"],"Dover","Delaware","DE",4.8,167,17,True,"1-2 days","$$","Dover foundation specialists for Delaware's sandy and clay soils. Waterproofing, helical piers, and drainage solutions for First State homeowners.",1900,["Sandy soil","Helical piers","Waterproofing","Central DE"]),
  ("ct212","Diamond State HVAC",["HVAC"],"Newark","Delaware","DE",4.7,198,12,True,"< 2 hours","$$","Newark HVAC for Northern Delaware and the Philadelphia suburb market. Heat pump installation, furnace replacement, and mini-split systems.",2100,["Heat pump","Mini-split","Furnace","Northern DE"]),
  ("ct213","Delaware Roofing Masters",["Roof","Exterior"],"Middletown","Delaware","DE",4.7,178,10,True,"Same day","$$","Middletown roofing and exterior for Central Delaware. Asphalt and metal roofing, storm damage repair, and vinyl siding replacement.",2000,["Metal roofing","Storm damage","Siding","Central DE"]),
  ("ct214","DE Home Services",["Interior","Exterior"],"Smyrna","Delaware","DE",4.5,156,7,True,"Same day","$","Smyrna general contractor for Central Delaware. Kitchen and bath remodels, deck construction, and interior updates for First State homeowners.",1700,["Kitchen remodel","Deck building","Interior","Central DE"]),

  # ── WEST VIRGINIA (WV) – missing: Electrical, HVAC, Plumbing, Roof ──────────
  ("ct215","Mountain State HVAC",["HVAC"],"Huntington","West Virginia","WV",4.7,178,13,True,"< 2 hours","$$","Huntington heating and cooling for the Tri-State area. Furnace replacement, heat pump installation, and emergency HVAC repair throughout Western WV.",2000,["Furnace","Heat pump","Emergency","Tri-State area"]),
  ("ct216","WV Roofing Experts",["Roof","Exterior"],"Parkersburg","West Virginia","WV",4.7,189,11,True,"Same day","$$","Parkersburg roofing for Northwestern West Virginia. Metal roofing for mountain homes, storm damage repair, and gutter installation.",2100,["Metal roofing","Mountain homes","Storm damage","NW West Virginia"]),
  ("ct217","WV Electric Solutions",["Electrical","Safety"],"Morgantown","West Virginia","WV",4.6,178,12,True,"< 3 hours","$$","Morgantown licensed electricians for North-Central WV. Panel upgrades, generator hookups, and EV charger installation near WVU.",1800,["Panel upgrade","Generator","EV charger","N-Central WV"]),
  ("ct218","WV Plumbing Masters",["Plumbing"],"Wheeling","West Virginia","WV",4.6,167,11,True,"< 2 hours","$$","Wheeling plumbing for the Northern Panhandle. Water heater replacement, frozen pipe emergencies, and drain cleaning throughout the Upper Ohio Valley.",1900,["Water heater","Frozen pipe","Drain cleaning","N Panhandle"]),

  # ── MAINE (ME) – missing: Electrical, Exterior, Foundation, Interior, Roof ───
  ("ct219","Pine Tree Foundation Repair",["Foundation"],"Bangor","Maine","ME",4.8,167,20,True,"1-2 days","$$","Bangor foundation specialists for Central Maine's granite bedrock and extreme freeze-thaw. Waterproofing, crawl space encapsulation, and drainage solutions.",2000,["Granite bedrock","Extreme freeze","Crawl space","Central ME"]),
  ("ct220","Maine Roofing Masters",["Roof","Exterior"],"Lewiston","Maine","ME",4.7,189,13,True,"1-2 days","$$","Lewiston roofing for Central Maine's heavy snow load conditions. Metal standing seam, ice dam prevention, and asphalt roofing for Maine homeowners.",2200,["Snow load","Ice dam","Metal roofing","Central ME"]),
  ("ct221","Maine Electric Pros",["Electrical","Safety"],"Auburn","Maine","ME",4.6,167,12,True,"< 3 hours","$$","Auburn licensed electricians for Androscoggin County. Panel upgrades, generator hookups, oil-to-heat-pump electrical, and EV charger installation.",1700,["Panel upgrade","Generator","Heat pump electrical","Androscoggin"]),
  ("ct222","Maine Home Services",["Interior","Exterior"],"Biddeford","Maine","ME",4.5,156,7,True,"Same day","$$","Biddeford general contractor for Southern Maine. Kitchen and bath remodels, deck construction, and weatherproofing for New England's coastal climate.",1800,["Kitchen remodel","Deck building","Weatherproofing","S Maine"]),

  # ── SOUTH DAKOTA (SD) – missing: Electrical, Foundation, HVAC, Roof ──────────
  ("ct223","South Dakota Foundation Repair",["Foundation"],"Rapid City","South Dakota","SD",4.8,145,18,True,"1-2 days","$$","Rapid City foundation specialists for Western South Dakota's expansive soil and freeze-thaw. Pier systems, waterproofing, and slab crack repair.",1700,["Expansive soil","Pier systems","Freeze-thaw","W South Dakota"]),
  ("ct224","Prairie State HVAC",["HVAC"],"Aberdeen","South Dakota","SD",4.7,167,12,True,"< 2 hours","$$","Aberdeen heating and cooling for Northeast South Dakota. Furnace replacement, heat pump installation, and emergency heating for extreme winters.",1900,["Furnace","Heat pump","Extreme winter","NE South Dakota"]),
  ("ct225","South Dakota Electric",["Electrical","Safety"],"Brookings","South Dakota","SD",4.6,145,11,True,"< 3 hours","$$","Brookings licensed electricians for East-Central South Dakota. Panel upgrades, generator hookups, and EV charger installation.",1600,["Panel upgrade","Generator","EV charger","E-Central SD"]),
  ("ct226","SD Roofing Experts",["Roof","Exterior"],"Watertown","South Dakota","SD",4.6,156,10,True,"Same day","$$","Watertown roofing for Northeast South Dakota. Hail and wind damage specialists, metal and asphalt roofing for harsh plains conditions.",1800,["Hail damage","Wind damage","Metal roofing","NE South Dakota"]),

  # ── NORTH DAKOTA (ND) – missing: Electrical, Exterior, Foundation, Interior, Roof ──
  ("ct227","North Dakota Foundation Repair",["Foundation"],"Bismarck","North Dakota","ND",4.8,134,19,True,"1-2 days","$$","Bismarck foundation specialists for North Dakota's extreme freeze-thaw and expansive soil. Helical piers, waterproofing, and frost wall repair.",1600,["Extreme freeze","Frost wall","Helical piers","SW North Dakota"]),
  ("ct228","Roughrider Roofing",["Roof","Exterior"],"Grand Forks","North Dakota","ND",4.7,156,11,True,"Same day","$$","Grand Forks roofing for Eastern North Dakota. Hail and blizzard damage specialists, metal and asphalt roofing for Red River Valley homeowners.",1800,["Blizzard damage","Hail","Metal roofing","Red River Valley"]),
  ("ct229","North Dakota Electric",["Electrical","Safety"],"Williston","North Dakota","ND",4.6,134,12,True,"< 3 hours","$$","Williston licensed electricians for Northwest North Dakota. Panel upgrades, generator hookups, and EV charger installation for the Bakken region.",1500,["Panel upgrade","Generator","EV charger","Bakken region"]),
  ("ct230","ND Home Services",["Interior","Exterior"],"Minot","North Dakota","ND",4.5,145,7,True,"Same day","$","Minot general contractor for North-Central North Dakota. Kitchen and bath remodels, deck construction, and three-season porch additions.",1600,["Kitchen remodel","Three-season porch","Deck building","N-Central ND"]),

  # ── ALASKA (AK) – missing: Exterior, Foundation, Interior, Roof ─────────────
  ("ct231","Alaska Foundation Specialists",["Foundation"],"Fairbanks","Alaska","AK",4.9,123,25,True,"1-2 days","$$$","Fairbanks permafrost and foundation engineers. Thermosyphon installation, helical pile systems, and frost jacking repair for Interior Alaska's extreme conditions.",1600,["Permafrost","Thermosyphon","Helical pile","Interior AK"]),
  ("ct232","Last Frontier Roofing",["Roof","Exterior"],"Juneau","Alaska","AK",4.8,145,18,True,"1-2 days","$$$","Juneau roofing specialists for Southeast Alaska's rain and heavy snow loads. Metal standing seam, structural snow removal, and emergency tarping.",1800,["Snow load","Metal roofing","Rain protection","SE Alaska"]),
  ("ct233","Alaska Home Renovations",["Interior","Exterior"],"Wasilla","Alaska","AK",4.7,167,11,True,"Same day","$$$","Wasilla general contractor for the Mat-Su Valley. Winter weatherization, insulation upgrades, and cabin renovation throughout South-Central Alaska.",1900,["Weatherization","Insulation","Cabin renovation","Mat-Su Valley"]),

  # ── VERMONT (VT) – missing: Electrical, Foundation, Interior, Plumbing ────────
  ("ct234","Vermont Foundation Repair",["Foundation"],"Rutland","Vermont","VT",4.8,145,19,True,"1-2 days","$$","Rutland foundation specialists for Vermont's granite bedrock and severe freeze-thaw. Waterproofing, helical piers, and interior drainage systems.",1700,["Granite bedrock","Severe freeze","Helical piers","Central VT"]),
  ("ct235","Green Mountain Electric",["Electrical","Safety"],"Barre","Vermont","VT",4.7,156,13,True,"< 3 hours","$$","Barre licensed electricians for Central Vermont. Panel upgrades, generator hookups, EV chargers, and oil-to-heat-pump electrical conversion.",1600,["Panel upgrade","Generator","EV charger","Central VT"]),
  ("ct236","Vermont Plumbing Masters",["Plumbing"],"St. Johnsbury","Vermont","VT",4.6,134,12,True,"< 2 hours","$$","St. Johnsbury plumbing for Northeast Vermont. Frozen pipe emergencies, water heater replacement, and well pump service for rural Vermont homeowners.",1500,["Frozen pipe","Well pump","Water heater","NE Vermont"]),
  ("ct237","VT Home Renovations",["Interior","Exterior"],"Middlebury","Vermont","VT",4.5,145,7,True,"Same day","$$","Middlebury general contractor for West-Central Vermont. Kitchen and bath remodels, barn conversion projects, and three-season porch additions.",1600,["Kitchen remodel","Barn conversion","Three-season porch","W-Central VT"]),

  # ── RHODE ISLAND (RI) – missing: Exterior, Foundation, HVAC, Interior, Plumbing, Roof ──
  ("ct238","Rhode Island Foundation Repair",["Foundation"],"Cranston","Rhode Island","RI",4.8,167,18,True,"1-2 days","$$$","Cranston foundation specialists for Rhode Island's coastal soil and freeze-thaw. Waterproofing, helical piers, and drainage solutions for Ocean State homes.",1900,["Coastal soil","Helical piers","Waterproofing","Providence area"]),
  ("ct239","Ocean State HVAC",["HVAC"],"Warwick","Rhode Island","RI",4.7,198,12,True,"< 2 hours","$$$","Warwick heating and cooling for Rhode Island. Heat pump installation, oil-to-heat-pump conversions, and ductless mini-splits for New England homes.",2100,["Heat pump","Oil conversion","Mini-split","S Rhode Island"]),
  ("ct240","Rhode Island Roofing",["Roof","Exterior"],"Pawtucket","Rhode Island","RI",4.7,178,11,True,"Same day","$$$","Pawtucket roofing for Northeast Rhode Island. Ice dam specialists, asphalt and slate roofing, and storm damage repair for New England coastal homes.",2000,["Ice dam","Slate roofing","Storm damage","NE Rhode Island"]),
  ("ct241","RI Plumbing Experts",["Plumbing"],"North Providence","Rhode Island","RI",4.6,167,10,True,"< 2 hours","$$$","North Providence plumbing for the Providence metro. Water heater replacement, frozen pipe emergencies, and drain cleaning throughout Rhode Island.",1900,["Water heater","Frozen pipe","Drain cleaning","Providence metro"]),
  ("ct242","RI Home Services",["Interior","Exterior"],"Cumberland","Rhode Island","RI",4.5,156,7,True,"Same day","$$$","Cumberland general contractor for Northern Rhode Island. Kitchen and bath remodels, deck construction, and basement finishing throughout the Ocean State.",1800,["Kitchen remodel","Deck building","Basement finish","N Rhode Island"]),

  # ── WYOMING (WY) – missing: Electrical, Exterior, Foundation, Interior, Roof ─
  ("ct243","Wyoming Foundation Repair",["Foundation"],"Casper","Wyoming","WY",4.8,112,20,True,"1-2 days","$$","Casper foundation specialists for Wyoming's expansive soil and severe freeze-thaw. Helical piers, slab leveling, and waterproofing for High Plains homeowners.",1400,["Expansive soil","Frost heave","Helical piers","Central WY"]),
  ("ct244","Cowboy State Roofing",["Roof","Exterior"],"Gillette","Wyoming","WY",4.7,134,12,True,"Same day","$$","Gillette roofing for Northeastern Wyoming's wind and hail conditions. Metal and impact-resistant roofing for the High Plains' extreme weather.",1600,["Wind damage","Hail","Metal roofing","NE Wyoming"]),
  ("ct245","Wyoming Electric Masters",["Electrical","Safety"],"Rock Springs","Wyoming","WY",4.6,112,11,True,"< 3 hours","$$","Rock Springs licensed electricians for Southwest Wyoming. Panel upgrades, generator hookups, solar wiring, and EV charger installation.",1300,["Panel upgrade","Generator","Solar wiring","SW Wyoming"]),
  ("ct246","Wyoming Home Services",["Interior","Exterior"],"Laramie","Wyoming","WY",4.5,123,7,True,"Same day","$$","Laramie general contractor for Southeast Wyoming. Kitchen and bath remodels, deck construction, and exterior updates for Wyoming homeowners.",1400,["Kitchen remodel","Deck building","Exterior","SE Wyoming"]),

  # ── TEXAS (TX) – missing: Electrical, Interior ──────────────────────────────
  ("ct247","Texas Electric Masters",["Electrical","Safety"],"San Antonio","Texas","TX",4.8,489,14,True,"< 2 hours","$$","San Antonio licensed master electricians. Panel upgrades, generator hookups for winter storm readiness, EV charger installation, and whole-home surge protection.",5200,["Generator","Winter readiness","EV charger","San Antonio metro"]),
  ("ct248","Lone Star Home Renovations",["Interior","Exterior"],"Plano","Texas","TX",4.7,412,9,True,"Same day","$$","Plano general contractor for DFW homeowners. Kitchen and bathroom remodels, outdoor living spaces, and patio covers throughout North Texas.",4800,["Kitchen remodel","Outdoor living","Patio cover","DFW metro"]),

  # ── MARYLAND (MD) – missing: Exterior, Foundation, Interior, Roof ───────────
  ("ct249","Maryland Foundation Repair",["Foundation"],"Frederick","Maryland","MD",4.8,234,18,True,"1-2 days","$$","Frederick foundation specialists for Western Maryland's limestone and clay conditions. Helical piers, basement waterproofing, and bowing wall repair.",2700,["Limestone","Clay soil","Helical piers","W Maryland"]),
  ("ct250","Old Line State Roofing",["Roof","Exterior"],"Rockville","Maryland","MD",4.7,289,12,True,"Same day","$$","Rockville roofing for the DC suburbs. Storm damage specialists, architectural shingle and metal roofing, and ice dam prevention for Mid-Atlantic homeowners.",3200,["Storm damage","DC suburbs","Metal roofing","Montgomery County"]),
  ("ct251","Maryland Home Renovations",["Interior","Exterior"],"Bowie","Maryland","MD",4.6,267,8,True,"Same day","$$","Bowie general contractor for Prince George's County. Kitchen and bath remodels, deck construction, and basement finishing near Washington DC.",2900,["Kitchen remodel","Deck building","DC adjacent","Prince George"]),

  # ── NEW JERSEY (NJ) – missing: Exterior, Foundation, Interior, Roof ──────────
  ("ct252","Jersey Foundation Repair",["Foundation"],"Trenton","New Jersey","NJ",4.8,289,19,True,"1-2 days","$$$","Trenton foundation specialists for Central New Jersey's sandy and clay soils. Waterproofing, helical piers, and basement crack injection.",2900,["Sandy soil","Helical piers","Crack injection","Central NJ"]),
  ("ct253","Garden State Roofing",["Roof","Exterior"],"Toms River","New Jersey","NJ",4.7,312,12,True,"Same day","$$$","Toms River roofing and exterior for the Jersey Shore. Storm and hurricane damage specialists, wind-rated installations, and siding replacement.",3600,["Storm damage","Hurricane","Wind-rated","Jersey Shore"]),
  ("ct254","NJ Home Renovations",["Interior","Exterior"],"Cherry Hill","New Jersey","NJ",4.6,345,8,True,"Same day","$$$","Cherry Hill general contractor for South Jersey. Kitchen and bath remodels, deck construction, and basement finishing throughout Burlington and Camden counties.",3900,["Kitchen remodel","Deck building","S Jersey","Basement finish"]),
]

def make_entry(e):
    id_, name, spec, city, state, abbr, rating, reviews, yrs, verified, response, price, bio, jobs, tags = e
    spec_str = ", ".join(f'"{s}"' for s in spec)
    tags_str = ", ".join(f'"{t}"' for t in tags)
    return f'  {{ id: "{id_}", name: "{name}", specialty: [{spec_str}], city: "{city}", state: "{state}", stateAbbr: "{abbr}", rating: {rating}, reviewCount: {reviews}, yearsInBusiness: {yrs}, verified: {"true" if verified else "false"}, responseTime: "{response}", priceRange: "{price}", bio: "{bio}", completedJobs: {jobs}, tags: [{tags_str}] }},'

new_ts = "\n" + "\n".join(make_entry(e) for e in new_contractors) + "\n"

with open('/Users/andrewdevyatkin/.gemini/antigravity-ide/scratch/lib/data.ts', 'r') as f:
    content = f.read()

# Find the contractors array closing ]; — it comes after the last ct60 entry
# Find the last contractor entry and insert before the following ];
# The contractors array ends with the ct60 (Wyoming) entry
marker = '  { id: "ct60"'
idx = content.find(marker)
if idx == -1:
    print("ERROR: ct60 not found")
else:
    end_of_line = content.find('\n', idx) + 1
    # Find the ]; that follows
    close_idx = content.find('\n];', end_of_line)
    if close_idx == -1:
        print("ERROR: closing ]; not found after ct60")
    else:
        new_content = content[:close_idx] + new_ts + content[close_idx:]
        with open('/Users/andrewdevyatkin/.gemini/antigravity-ide/scratch/lib/data.ts', 'w') as f:
            f.write(new_content)
        count = len(new_contractors)
        total = new_content.count('stateAbbr:')
        print(f"SUCCESS: Added {count} contractors. Total now: {total}")
