import re

new_contractors = r"""  // Virginia
  { id: "ct23", name: "Old Dominion Plumbing",          specialty: ["Plumbing","HVAC"],                 city: "Richmond",        state: "Virginia",       stateAbbr: "VA", rating: 4.7, reviewCount: 298, yearsInBusiness: 20, verified: true,  responseTime: "< 2 hours",  priceRange: "$$",  bio: "Full-service plumbing and HVAC for the Richmond metro and Northern Virginia. Water heater replacements, pipe repairs, and central AC installations.", completedJobs: 3400, tags: ["Licensed","Insured","Free estimates","Northern VA"] },
  // Tennessee
  { id: "ct24", name: "Music City Home Repair",         specialty: ["Interior","Exterior","Plumbing"],  city: "Nashville",       state: "Tennessee",      stateAbbr: "TN", rating: 4.6, reviewCount: 387, yearsInBusiness: 7,  verified: true,  responseTime: "Same day",   priceRange: "$",   bio: "Nashville top-rated general contractor for bathroom remodels, kitchen updates, and plumbing repairs. No-nonsense pricing, always on time.", completedJobs: 4200, tags: ["Bathroom remodel","Kitchen update","Same-day","Nashville metro"] },
  // Michigan
  { id: "ct25", name: "Great Lakes Electrical",         specialty: ["Electrical","Safety"],             city: "Detroit",         state: "Michigan",       stateAbbr: "MI", rating: 4.7, reviewCount: 341, yearsInBusiness: 18, verified: true,  responseTime: "< 3 hours",  priceRange: "$$",  bio: "Detroit-area master electricians. Panel upgrades, knob-and-tube replacement, EV charger installs, and smart home wiring.", completedJobs: 2800, tags: ["Master Electrician","EV charger","Smart home","Detroit area"] },
  // Minnesota
  { id: "ct26", name: "North Star HVAC and Insulation", specialty: ["HVAC"],                            city: "Minneapolis",      state: "Minnesota",      stateAbbr: "MN", rating: 4.8, reviewCount: 263, yearsInBusiness: 15, verified: true,  responseTime: "< 2 hours",  priceRange: "$$",  bio: "Cold-climate HVAC specialists. Boiler repair, furnace replacement, heat pumps, and spray foam insulation. We know Minnesota winters.", completedJobs: 2600, tags: ["Boiler specialist","Cold-climate","Spray foam","Minneapolis area"] },
  // Massachusetts
  { id: "ct27", name: "Bay State Roofing",              specialty: ["Roof","Exterior"],                 city: "Boston",          state: "Massachusetts",  stateAbbr: "MA", rating: 4.7, reviewCount: 445, yearsInBusiness: 25, verified: true,  responseTime: "1-2 days",   priceRange: "$$$", bio: "New England roofing specialists with 25 years in the Boston market. Slate, asphalt, flat roofs, and ice dam prevention systems.", completedJobs: 6100, tags: ["Slate roofing","Ice dam prevention","Flat roof","New England"] },
  // Maryland
  { id: "ct28", name: "Chesapeake Home Services",       specialty: ["Plumbing","HVAC","Electrical"],    city: "Baltimore",       state: "Maryland",       stateAbbr: "MD", rating: 4.6, reviewCount: 312, yearsInBusiness: 12, verified: true,  responseTime: "< 2 hours",  priceRange: "$$",  bio: "Baltimore one-call home service company. Licensed plumbers, HVAC techs, and electricians under one roof. Serving Baltimore, Annapolis, and the DMV.", completedJobs: 3900, tags: ["One-call service","Licensed","DMV area","Financing available"] },
  // South Carolina
  { id: "ct29", name: "Palmetto State Roofing",         specialty: ["Roof","Exterior"],                 city: "Charleston",      state: "South Carolina", stateAbbr: "SC", rating: 4.7, reviewCount: 289, yearsInBusiness: 10, verified: true,  responseTime: "Same day",   priceRange: "$$",  bio: "Storm and hurricane damage specialists serving the Lowcountry. We work directly with your insurance adjuster. Free inspection and estimate.", completedJobs: 3800, tags: ["Hurricane damage","Insurance specialist","Lowcountry","Free inspection"] },
  // Louisiana
  { id: "ct30", name: "Bayou City Plumbing",            specialty: ["Plumbing","Foundation"],           city: "New Orleans",     state: "Louisiana",      stateAbbr: "LA", rating: 4.6, reviewCount: 201, yearsInBusiness: 22, verified: true,  responseTime: "< 1 hour",   priceRange: "$$",  bio: "New Orleans plumbing and slab leak specialists. We understand below-sea-level foundation work and high-humidity pipe issues.", completedJobs: 2900, tags: ["Slab leak","24/7","Flood damage","New Orleans area"] },
  // Oregon
  { id: "ct31", name: "Pacific Crest HVAC",             specialty: ["HVAC","Electrical"],               city: "Portland",        state: "Oregon",         stateAbbr: "OR", rating: 4.7, reviewCount: 234, yearsInBusiness: 11, verified: true,  responseTime: "< 3 hours",  priceRange: "$$",  bio: "Portland heat pump and mini-split specialists. We handle utility rebate applications, ductless systems, and EV charger installations.", completedJobs: 1900, tags: ["Heat pump","Mini-split","EV charger","Portland metro"] },
  // Indiana
  { id: "ct32", name: "Hoosier Home Repair",            specialty: ["Interior","Exterior","Plumbing"],  city: "Indianapolis",    state: "Indiana",        stateAbbr: "IN", rating: 4.5, reviewCount: 467, yearsInBusiness: 9,  verified: true,  responseTime: "Same day",   priceRange: "$",   bio: "Indianapolis-area general contractor. Deck builds, bathroom remodels, plumbing repairs, and drywall work. Honest hourly rates.", completedJobs: 5100, tags: ["No hidden fees","Deck building","Bathroom remodel","Indianapolis"] },
  // Missouri
  { id: "ct33", name: "Gateway HVAC Solutions",         specialty: ["HVAC"],                            city: "St. Louis",       state: "Missouri",       stateAbbr: "MO", rating: 4.6, reviewCount: 319, yearsInBusiness: 14, verified: true,  responseTime: "< 2 hours",  priceRange: "$$",  bio: "St. Louis HVAC repair and replacement. Furnace, AC, heat pump, and ductwork specialists. Financing available with approved credit.", completedJobs: 2700, tags: ["Financing","Ductwork","Furnace specialist","St. Louis area"] },
  // Wisconsin
  { id: "ct34", name: "Badger State Electrical",        specialty: ["Electrical","Safety"],             city: "Milwaukee",       state: "Wisconsin",      stateAbbr: "WI", rating: 4.7, reviewCount: 188, yearsInBusiness: 16, verified: true,  responseTime: "< 3 hours",  priceRange: "$$",  bio: "Milwaukee and SE Wisconsin licensed electricians. Panel upgrades, generator installs, EV chargers, and commercial wiring.", completedJobs: 2100, tags: ["Generator install","EV charger","Panel upgrade","SE Wisconsin"] },
  // Nevada
  { id: "ct35", name: "Silver State Plumbing",          specialty: ["Plumbing","HVAC"],                 city: "Las Vegas",       state: "Nevada",         stateAbbr: "NV", rating: 4.7, reviewCount: 543, yearsInBusiness: 13, verified: true,  responseTime: "< 1 hour",   priceRange: "$$",  bio: "Las Vegas 24/7 plumbing and AC repair. Desert climate specialists handling swamp cooler conversions, water softeners, and emergency AC repairs.", completedJobs: 6200, tags: ["24/7","Swamp cooler","Water softener","Las Vegas area"] },
  // Utah
  { id: "ct36", name: "Wasatch Front Roofing",          specialty: ["Roof","Exterior"],                 city: "Salt Lake City",  state: "Utah",           stateAbbr: "UT", rating: 4.8, reviewCount: 276, yearsInBusiness: 12, verified: true,  responseTime: "1-2 days",   priceRange: "$$",  bio: "Utah top-rated roofing company. Specializing in snow and wind damage repair, metal roofing, and energy-efficient installations.", completedJobs: 3100, tags: ["Metal roofing","Snow damage","Energy-efficient","Wasatch Front"] },
  // New Mexico
  { id: "ct37", name: "Land of Enchantment Electric",   specialty: ["Electrical","HVAC"],               city: "Albuquerque",     state: "New Mexico",     stateAbbr: "NM", rating: 4.6, reviewCount: 167, yearsInBusiness: 10, verified: true,  responseTime: "< 3 hours",  priceRange: "$$",  bio: "Albuquerque licensed electricians and HVAC techs. Solar panel wiring, evaporative cooler service, and panel upgrades for New Mexico homeowners.", completedJobs: 1800, tags: ["Solar wiring","Evaporative cooler","Panel upgrade","ABQ area"] },
  // Kansas
  { id: "ct38", name: "Sunflower Home Services",        specialty: ["Plumbing","Interior"],             city: "Wichita",         state: "Kansas",         stateAbbr: "KS", rating: 4.5, reviewCount: 214, yearsInBusiness: 8,  verified: true,  responseTime: "< 2 hours",  priceRange: "$",   bio: "Wichita plumbing and remodeling. Bathroom and kitchen updates, water heater installs, and storm damage repairs. Family-owned and operated.", completedJobs: 2200, tags: ["Family-owned","Storm damage","Bathroom remodel","Wichita area"] },
  // Kentucky
  { id: "ct39", name: "Bluegrass HVAC and Plumbing",    specialty: ["HVAC","Plumbing"],                 city: "Louisville",      state: "Kentucky",       stateAbbr: "KY", rating: 4.6, reviewCount: 298, yearsInBusiness: 17, verified: true,  responseTime: "< 2 hours",  priceRange: "$$",  bio: "Louisville HVAC and plumbing specialists. Furnace and AC replacement, water heater installs, and drain cleaning. 24/7 emergency service.", completedJobs: 3300, tags: ["24/7 emergency","Drain cleaning","Furnace replacement","Louisville area"] },
  // Oklahoma
  { id: "ct40", name: "Sooner State Foundation Repair", specialty: ["Foundation","Roof"],               city: "Oklahoma City",   state: "Oklahoma",       stateAbbr: "OK", rating: 4.7, reviewCount: 189, yearsInBusiness: 21, verified: true,  responseTime: "1-2 days",   priceRange: "$$",  bio: "Oklahoma foundation and storm damage specialists. Tornado damage repair, pier and beam systems, and crawl space encapsulation.", completedJobs: 2800, tags: ["Tornado damage","Pier and beam","Crawl space","OKC metro"] },
  // Iowa
  { id: "ct41", name: "Hawkeye Home Repair",            specialty: ["Interior","Exterior","HVAC"],      city: "Des Moines",      state: "Iowa",           stateAbbr: "IA", rating: 4.5, reviewCount: 167, yearsInBusiness: 9,  verified: true,  responseTime: "Same day",   priceRange: "$",   bio: "Des Moines general contractor for home repairs and HVAC maintenance. No job too small, from furnace tune-ups to full basement finishes.", completedJobs: 2600, tags: ["No job too small","Basement finishing","Furnace tune-up","Des Moines"] },
  // Mississippi
  { id: "ct42", name: "Magnolia State Roofing",         specialty: ["Roof","Exterior"],                 city: "Jackson",         state: "Mississippi",    stateAbbr: "MS", rating: 4.6, reviewCount: 201, yearsInBusiness: 14, verified: true,  responseTime: "Same day",   priceRange: "$",   bio: "Jackson-area roofing and storm damage repair. We handle insurance claims, metal roofing, and emergency tarping after severe weather.", completedJobs: 2400, tags: ["Storm damage","Metal roofing","Insurance claims","Central MS"] },
  // Alabama
  { id: "ct43", name: "Heart of Dixie Plumbing",        specialty: ["Plumbing","HVAC"],                 city: "Birmingham",      state: "Alabama",        stateAbbr: "AL", rating: 4.6, reviewCount: 312, yearsInBusiness: 13, verified: true,  responseTime: "< 2 hours",  priceRange: "$$",  bio: "Birmingham plumbing and HVAC. Water heater replacement, AC repair, and sewer line service for the greater Birmingham area.", completedJobs: 3100, tags: ["Water heater","AC repair","Sewer line","Birmingham area"] },
  // Arkansas
  { id: "ct44", name: "Natural State Electrical",       specialty: ["Electrical"],                      city: "Little Rock",     state: "Arkansas",       stateAbbr: "AR", rating: 4.5, reviewCount: 143, yearsInBusiness: 11, verified: true,  responseTime: "< 3 hours",  priceRange: "$$",  bio: "Little Rock licensed electricians. Residential panel upgrades, outlet installation, generator hookups, and electrical troubleshooting.", completedJobs: 1600, tags: ["Panel upgrade","Generator hookup","Licensed","Little Rock"] },
  // New Jersey
  { id: "ct45", name: "Garden State Home Services",     specialty: ["Plumbing","HVAC","Electrical"],    city: "Newark",          state: "New Jersey",     stateAbbr: "NJ", rating: 4.7, reviewCount: 489, yearsInBusiness: 19, verified: true,  responseTime: "< 2 hours",  priceRange: "$$$", bio: "Northern New Jersey full-service home contractor. Licensed plumbers, electricians, and HVAC techs available same day. Serving Essex, Hudson, and Bergen counties.", completedJobs: 5800, tags: ["Same day","Licensed","Full service","Northern NJ"] },
  // Connecticut
  { id: "ct46", name: "Constitution State Roofing",     specialty: ["Roof","Exterior"],                 city: "Hartford",        state: "Connecticut",    stateAbbr: "CT", rating: 4.7, reviewCount: 234, yearsInBusiness: 16, verified: true,  responseTime: "1-2 days",   priceRange: "$$$", bio: "Hartford and Connecticut roofing specialists. Slate, cedar shake, asphalt, and flat roofing for New England climate. Ice dam removal and prevention.", completedJobs: 2900, tags: ["Slate roofing","Ice dam","Cedar shake","Connecticut statewide"] },
  // Nebraska
  { id: "ct47", name: "Cornhusker Plumbing and HVAC",   specialty: ["Plumbing","HVAC"],                 city: "Omaha",           state: "Nebraska",       stateAbbr: "NE", rating: 4.6, reviewCount: 198, yearsInBusiness: 12, verified: true,  responseTime: "< 2 hours",  priceRange: "$$",  bio: "Omaha plumbing and HVAC specialists. Furnace replacement, AC installation, water heater service, and 24/7 emergency pipe repair.", completedJobs: 2400, tags: ["24/7 emergency","Furnace replacement","Water heater","Omaha area"] },
  // Idaho
  { id: "ct48", name: "Gem State Electrical",           specialty: ["Electrical","HVAC"],               city: "Boise",           state: "Idaho",          stateAbbr: "ID", rating: 4.7, reviewCount: 156, yearsInBusiness: 9,  verified: true,  responseTime: "< 3 hours",  priceRange: "$$",  bio: "Boise electricians and HVAC techs. New construction wiring, panel upgrades, heat pump installations, and EV charger installs.", completedJobs: 1700, tags: ["Heat pump","EV charger","New construction","Treasure Valley"] },
  // Hawaii
  { id: "ct49", name: "Aloha Home Repair",              specialty: ["Plumbing","Interior","Exterior"],  city: "Honolulu",        state: "Hawaii",         stateAbbr: "HI", rating: 4.8, reviewCount: 287, yearsInBusiness: 15, verified: true,  responseTime: "< 2 hours",  priceRange: "$$$", bio: "Honolulu trusted general contractor. Plumbing repairs, lanai construction, hurricane strapping, and tropical moisture damage remediation.", completedJobs: 2100, tags: ["Hurricane prep","Lanai construction","Moisture damage","Oahu"] },
  // Montana
  { id: "ct50", name: "Big Sky Roofing and Repair",     specialty: ["Roof","Exterior","HVAC"],          city: "Billings",        state: "Montana",        stateAbbr: "MT", rating: 4.7, reviewCount: 134, yearsInBusiness: 18, verified: true,  responseTime: "1-2 days",   priceRange: "$$",  bio: "Montana roofing, HVAC, and exterior specialists. Metal roofing, snow load engineering, and wood stove installs for Big Sky homeowners.", completedJobs: 1900, tags: ["Metal roofing","Snow load","Wood stove","Statewide MT"] },
  // New Hampshire
  { id: "ct51", name: "Granite State Plumbing",         specialty: ["Plumbing","HVAC"],                 city: "Manchester",      state: "New Hampshire",  stateAbbr: "NH", rating: 4.7, reviewCount: 145, yearsInBusiness: 14, verified: true,  responseTime: "< 2 hours",  priceRange: "$$",  bio: "Manchester and southern NH plumbing and heating. Oil-to-gas conversions, radiant heating, water softeners, and emergency pipe repairs.", completedJobs: 1800, tags: ["Oil-to-gas conversion","Radiant heating","Water softener","Southern NH"] },
  // Delaware
  { id: "ct52", name: "First State Home Services",      specialty: ["Electrical","Plumbing"],           city: "Wilmington",      state: "Delaware",       stateAbbr: "DE", rating: 4.6, reviewCount: 178, yearsInBusiness: 11, verified: true,  responseTime: "< 3 hours",  priceRange: "$$",  bio: "Wilmington and Delaware licensed electricians and plumbers. Panel upgrades, outlet installation, water heater replacements, and drain service.", completedJobs: 1900, tags: ["Panel upgrade","Licensed","Water heater","Delaware statewide"] },
  // West Virginia
  { id: "ct53", name: "Mountain State Contractors",     specialty: ["Foundation","Interior","Exterior"], city: "Charleston",      state: "West Virginia",  stateAbbr: "WV", rating: 4.5, reviewCount: 132, yearsInBusiness: 16, verified: true,  responseTime: "1-2 days",   priceRange: "$$",  bio: "Charleston WV contractor specializing in foundation repair, basement waterproofing, and storm damage restoration for mountain terrain homes.", completedJobs: 1700, tags: ["Foundation repair","Waterproofing","Storm damage","WV statewide"] },
  // Maine
  { id: "ct54", name: "Pine Tree Plumbing and Heating", specialty: ["Plumbing","HVAC"],                 city: "Portland",        state: "Maine",          stateAbbr: "ME", rating: 4.8, reviewCount: 167, yearsInBusiness: 22, verified: true,  responseTime: "< 2 hours",  priceRange: "$$",  bio: "Portland Maine plumbing and heating. Oil boiler service, heat pump installs, water heater replacement, and frozen pipe emergencies.", completedJobs: 2300, tags: ["Oil boiler","Heat pump","Frozen pipe","Southern Maine"] },
  // South Dakota
  { id: "ct55", name: "Mount Rushmore Home Repair",     specialty: ["Interior","Exterior","Plumbing"],  city: "Sioux Falls",     state: "South Dakota",   stateAbbr: "SD", rating: 4.6, reviewCount: 112, yearsInBusiness: 8,  verified: true,  responseTime: "Same day",   priceRange: "$",   bio: "Sioux Falls general contractor. Bathroom and kitchen remodels, deck construction, plumbing repairs, and hail damage restoration.", completedJobs: 1400, tags: ["Hail damage","Deck construction","Bathroom remodel","Sioux Falls"] },
  // North Dakota
  { id: "ct56", name: "Peace Garden Heating and Cooling",specialty: ["HVAC","Plumbing"],               city: "Fargo",           state: "North Dakota",   stateAbbr: "ND", rating: 4.7, reviewCount: 98,  yearsInBusiness: 19, verified: true,  responseTime: "< 2 hours",  priceRange: "$$",  bio: "Fargo HVAC and plumbing for North Dakota extreme climate. Furnace replacement, geothermal systems, and emergency frozen pipe thawing.", completedJobs: 1600, tags: ["Geothermal","Frozen pipe","Furnace replacement","Fargo area"] },
  // Alaska
  { id: "ct57", name: "Last Frontier Home Services",    specialty: ["Plumbing","HVAC","Electrical"],    city: "Anchorage",       state: "Alaska",         stateAbbr: "AK", rating: 4.8, reviewCount: 143, yearsInBusiness: 24, verified: true,  responseTime: "< 3 hours",  priceRange: "$$$", bio: "Anchorage full-service home contractor. Experienced with permafrost foundation challenges, heating system failures, and extreme cold plumbing.", completedJobs: 2100, tags: ["Permafrost","Extreme cold","Emergency service","Anchorage area"] },
  // Vermont
  { id: "ct58", name: "Green Mountain Roofing",         specialty: ["Roof","Exterior","HVAC"],          city: "Burlington",      state: "Vermont",        stateAbbr: "VT", rating: 4.7, reviewCount: 119, yearsInBusiness: 13, verified: true,  responseTime: "1-2 days",   priceRange: "$$",  bio: "Burlington Vermont roofing and heating. Metal roofing, wood pellet boilers, heat pump installs, and energy efficiency upgrades.", completedJobs: 1500, tags: ["Metal roofing","Wood pellet","Heat pump","Vermont statewide"] },
  // Rhode Island
  { id: "ct59", name: "Ocean State Electrical",         specialty: ["Electrical","Safety"],             city: "Providence",      state: "Rhode Island",   stateAbbr: "RI", rating: 4.7, reviewCount: 167, yearsInBusiness: 12, verified: true,  responseTime: "< 3 hours",  priceRange: "$$$", bio: "Providence RI licensed electricians. Panel upgrades, knob-and-tube replacement, EV charger installs, and smart home automation wiring.", completedJobs: 1800, tags: ["K&T replacement","EV charger","Smart home","Rhode Island statewide"] },
  // Wyoming
  { id: "ct60", name: "Cowboy State Plumbing",          specialty: ["Plumbing","HVAC"],                 city: "Cheyenne",        state: "Wyoming",        stateAbbr: "WY", rating: 4.6, reviewCount: 87,  yearsInBusiness: 16, verified: true,  responseTime: "< 2 hours",  priceRange: "$$",  bio: "Cheyenne plumbing and HVAC. Well pump service, propane heating systems, water heater replacement, and emergency freeze repairs.", completedJobs: 1200, tags: ["Well pump","Propane heating","Freeze repair","Cheyenne area"] },
"""

with open('/Users/andrewdevyatkin/.gemini/antigravity-ide/scratch/lib/data.ts', 'r') as f:
    content = f.read()

pattern = r'(  \{ id: "ct22".*?\},\n)\];'
replacement = r'\g<1>' + new_contractors + '];'
new_content = re.sub(pattern, replacement, content, count=1, flags=re.DOTALL)

if new_content == content:
    print("ERROR: Pattern not found")
else:
    with open('/Users/andrewdevyatkin/.gemini/antigravity-ide/scratch/lib/data.ts', 'w') as f:
        f.write(new_content)
    count = new_content.count('stateAbbr:')
    print(f"SUCCESS: Total contractors = {count}")
